spring:
  application:
    name: ofo-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://security-service:8080
          predicates:
            - Path=/login
            - Method=POST
            
        - id: restaurant-service
          uri: http://restaurant-service:8081
          predicates:
            - Path=/restaurant/**
            
        - id: search-service
          uri: http://search-service:8082
          predicates:
            - Path=/search/**

        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
            
        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/order/**
            
        - id: payment-service
          uri: http://payment-service:8085
          predicates:
            - Path=/payment/**
            
        - id: review-service
          uri: http://review-service:8086
          predicates:
            - Path=/review/**